config/routes.rb
RailsbridgeSite2013::Application.routes.draw do

  root to: 'static_pages#home'

  get '/about',               to: 'static_pages#about',              as: 'about'
  get '/about/team',          to: 'static_pages#team',               as: 'team'
  get '/about/sponsors',      to: 'static_pages#sponsors',           as: 'sponsors'
  get '/about/chapters',      to: 'static_pages#chapters',           as: 'chapters'
  get '/about/past-events',   to: 'static_pages#past_events',        as: 'past_events'
  get '/about/projects',      to: 'static_pages#projects',           as: 'projects'
  get '/about/brand',         to: 'static_pages#brand',              as: 'brand'

  get '/help',                to: 'static_pages#help',               as: 'help'
  get '/help/teach',          to: 'static_pages#teach',              as: 'teach'
  get '/help/teacher-advice', to: 'static_pages#teacher_advice',     as: 'teacher_advice'
  get '/help/organize',       to: 'static_pages#organize',           as: 'organize'
  get '/help/host',           to: 'static_pages#host',               as: 'host'
  get '/help/donor-faq',      to: 'static_pages#donor_faq',          as: 'donor_faq'
  get '/help/interest-form',  to: 'static_pages#interest_form',      as: 'interest_form'
  get '/help/donate',         to: 'static_pages#donate',             as: 'donate'

  get '/learn',               to: 'static_pages#learn',              as: 'learn'
  get '/learn/resources',     to: 'static_pages#learning_resources', as: 'learning_resources'
  get '/learn/faq',           to: 'static_pages#learning_faq',       as: 'learning_faq'
  get '/learn/events',        to: 'static_pages#events',             as: 'events'

  get '/sitemap',             to: 'logistics#sitemap',               as: 'sitemap'

  unless Rails.application.config.consider_all_requests_local
    all_verbs = [:get, :post, :patch, :put, :delete]
    match '/404', to: 'logistics#error_404', as: 'error_404', via: all_verbs
    match '/500', to: 'logistics#error_500', as: 'error_500', via: all_verbs
  end
end

app/models/event.rb
class Event
  RAILSBRIDGE_ORGANIZATION_ID = 1

  class << self
    def sorted_events(state = nil, options = {})
      events = (state == :upcoming) ? upcoming_events(options) : past_events(options)
      sort_by_starts_at(events)
    end

    private

    def of_type(type, options = {})
      events = begin
        fetch_json({type: type}.merge(options))
      rescue StandardError => e
        puts "Error fetching events from BridgeTroll: #{e.message}"
      end
      events || []
    end

    def upcoming_events(options = {})
      of_type('upcoming', options)
    end

    def past_events(options = {})
      of_type('past', options).select { |event| event['workshop'] }
    end

    def sort_by_starts_at(events)
      events.sort_by { |event| event['sessions'].first['starts_at'].to_time }
    end

    def fetch_json(options)
      uri = URI::parse(BRIDGETROLL_URL)
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true
      response = http.send(:get, "/events.json?#{options.to_query}")
      JSON.parse(response.body)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery
  before_action :assign_nav_group

  private

  def assign_nav_group
    group = request.path.split('/')
    if group[1] && nav_links_by_group.keys.include?(group[1].to_sym)
      @nav_group = group[1].to_sym
    else
      @nav_group = false
    end
  end
end

app/controllers/logistics_controller.rb
class LogisticsController < ApplicationController

  def sitemap
  end

  def error_404
  end

  def error_500
    render layout: false
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :assign_upcoming_events, only: [:home, :events]

  def home
  end

  def about
  end

  def brand
  end

  def learn
  end

  def teach
  end

  def teacher_advice
  end

  def organize
  end

  def host
  end

  def faq
  end

  def projects
  end

  def learning_resources
  end

  def chapters
  end

  def events
  end

  def past_events
    @past_events = Event.sorted_events(:past, organization_id: Event::RAILSBRIDGE_ORGANIZATION_ID).map do |event|
      EventPresenter.new(event)
    end
  end

  def team
  end

  def sponsors
  end

  def help
  end

  def interest_form
  end

  private

  def assign_upcoming_events
    all_events = Event.sorted_events(:upcoming).map do |event|
      EventPresenter.new(event)
    end
    @railsbridge_events, @other_events = all_events.partition do |e|
      e.organization == 'RailsBridge'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title = nil)
    base_title = "RailsBridge"
    title ? "#{base_title} | #{title.join(' | ')}" : base_title
  end

  def nav_links_by_group
    {
      learn: [
        ["Overview", :learn],
        ["Upcoming Workshops", :events],
        ["FAQ", :learning_faq],
        ["Keep Learning", :learning_resources],
      ],
      help: [
        ["Overview", :help],
        ["Teach or TA", :teach],
        ["Teacher Advice", :teacher_advice],
        ["Organize an Event", :organize],
        ["Host an Event", :host],
        ["Donate", :donate],
        ["Donor FAQ", :donor_faq],
        ["Interest Form", :interest_form]
      ],
      about: [
        ["Overview", :about],
        ["Team", :team],
        ["Sponsors ", :sponsors],
        ["Chapters", :chapters],
        ["Past Events", :past_events],
        ["Projects", :projects],
        ["Brand", :brand]
      ]
    }
  end

  def nav_link(link_text, link)
    class_name = current_page?(link) ? 'is-selected' : ''
    content_tag(:li, class: class_name) do
      link_to link_text, link
    end
  end
end

app/views/layouts/_event.html.haml
- present(event) do |event_presenter|
  .event.js-match-height-item
    %h4= event.title
    %ul
      %li
        .event-date= event_presenter.event_dates
        .event-location= event_presenter.location_city
      %li
        %span.fa.fa-user
        = "Organized by #{event_presenter.organizers.first} & friends"
      %li
        = link_to event_presenter.location_url, class: 'event-venue', target: '_blank' do
          - if event_presenter.valid_location?
            %span.fa.fa-map-marker
          - if event.location.try(:name)
            = "Held at #{event.location.name}"

      .event-cta
        = link_to event_presenter.signup_link, event_presenter.event_url, target: '_blank'

app/views/layouts/_events.html.haml
- if @events.present?
  - count = 0
  - event_count = @events.count
  - span_count = 12 / events_per_row
  - event_modulus = event_count % events_per_row

  - @events.each_slice(events_per_row) do |event_row|
    .row.js-match-height
      - event_row.each do |event|
        %div{ class: "col-md-#{span_count}" }
          = render 'layouts/event', event: event
        - if event_modulus > 0 && event_count == (count += 1)
          %div{ class: "col-md-#{span_count}"}
            = render 'layouts/event_help'

  - if event_modulus == 0
    .row
      %div{ class: "col-md-#{span_count}" }
        = render 'layouts/event_help'
- else
  %p Please visit #{ link_to "Bridge Troll", "http://www.bridgetroll.org/" } for our list of current events.

app/views/layouts/_footer.html.haml
.footer
  .container
    .row
      .col-md-7
        %h2 Making Tech Better Since 2009
        %p
          RailsBridge is working to make tech more diverse and welcoming by
          teaching programming, connecting human beings, and listening to people's needs.
          We organize and teach free workshops on Rails, Ruby, and HTML &amp; CSS in
          cities all over the world, targeted at groups of people that are underrepresented in tech.
          You can read our code of conduct
          = link_to "here.", "http://bridgefoundry.org/code-of-conduct", class: "inline-link highlight"
        %p
          Want to suggest an update to this site? We use GitHub to keep track of our code.
          =render 'shared/github_links'
      .col-md-5
        %ul.footer-icons
          %li= link_to "", "https://github.com/railsbridge", class: "fa fa-github-square"
          %li= link_to "", "https://twitter.com/railsbridge", class: "fa fa-twitter-square"
          %li= link_to "", "https://www.facebook.com/railsbridge", class: "fa fa-facebook-square"
        %p.footer-email= link_to "Donate to RailsBridge", donate_path
        %p.footer-email= mail_to "hello@railsbridge.org", "hello@railsbridge.org"

app/views/layouts/_header.html.haml
.header.navbar.navbar-static-top
  .container
    = link_to '', :root, class: "logo"
    %ul.header-nav.nav.navbar-nav
      %li#learn.nav-link{ class: ("is-selected" if @nav_group == :learn) }
        = link_to "Learn", :learn
        %span
        %ul.dropdown-menu{ role: "menu" }
          = render "layouts/nav_links", nav_group: :learn
      %li#help.nav-link{ class: ("is-selected" if @nav_group == :help) }
        = link_to "Help", :help
        %span
        %ul.dropdown-menu{ role: "menu" }
          = render "layouts/nav_links", nav_group: :help
      %li#about.nav-link{ class: ("is-selected" if @nav_group == :about) }
        = link_to "About", :about
        %span
        %ul.dropdown-menu{ role: "menu" }
          = render "layouts/nav_links", nav_group: :about
      %li.external#blog= link_to "Blog", "http://blog.railsbridge.org/", target: "_blank"
      %li.external#curriculum= link_to "Curriculum & Installfest", "http://docs.railsbridge.org", target: "_blank"

app/views/layouts/_home_header.html.haml
.jumbotron
  .home-header
    .home-background
    .container
      .big-floaty-box
        %h1 Learn to code or level up with RailsBridge!
        %p RailsBridge workshops are a free and fun way to get started or level up with Rails, Ruby, and other web technologies. Our events focus on increasing diversity in tech, so that people of all backgrounds can feel welcome and comfortable in our industry.

app/views/layouts/_nav_links.html.haml
- nav_links_by_group[nav_group].each do |(link_title, link)|
  = nav_link link_title, link

app/views/layouts/_sidenav.html.erb
<!-- <ul class="nav nav-tabs nav-stacked sidenav">
  <li><%= link_to 'Upcoming Workshops', events_path %></li>
  <li><%= link_to 'Before Attending', learning_path %></li>
  <li><%= link_to 'FAQ', learning_faq_path %></li>
  <li><%= link_to 'Keep Learning', learning_resources_path %></li>
</ul>

<ul class="nav nav-tabs nav-stacked sidenav">
  <li class='active'><%= link_to 'Upcoming Workshops', root_path %></li>
  <li><%= link_to 'Chapters', root_path %></li>
  <li><%= link_to 'Before Attending', root_path %></li>
</ul>

<ul class="nav nav-tabs nav-stacked sidenav">
  <li class='active'><%= link_to 'Upcoming Workshops', root_path %></li>
  <li><%= link_to 'Chapters', root_path %></li>
  <li><%= link_to 'Before Attending', root_path %></li>
</ul> -->

app/views/layouts/_subnav.html.haml
.subnav
  .container
    %ul
      = render "layouts/nav_links", nav_group: @nav_group unless @nav_group.blank?

app/views/layouts/_topnav.html.erb
<div class="sub_nav">
  <div class="container">
    <ul class="topnav">
      <%= nav_link "Overview", learning_path %>
      <%= nav_link 'Upcoming Workshops', events_path %>
      <%= nav_link 'Before Attending', learning_path %>
      <%= nav_link 'FAQ', learning_faq_path %>
      <%= nav_link 'Keep Learning', learning_resources_path %>
    </ul>
  </div>
</div>

<div class="sub_nav">
  <div class="container">
    <ul class="topnav">
      <%= nav_link "Overview", about_path %>
      <%= nav_link "Team", team_path %>
      <%= nav_link "Sponsors ", sponsors_path %>
      <%= nav_link "Chapters", chapters_path %>
      <%= nav_link "Past Events", past_events_path %>
      <%= nav_link "Projects", projects_path %>
    </ul>
  </div>
</div>

<div class="sub_nav">
  <div class="container">
    <ul class="topnav">
      <%= nav_link 'Overview', helping_path %>
      <%= nav_link 'Teach or TA', teaching_path %>
      <%= nav_link 'Organize an Event', organizing_path %>
      <%= nav_link 'Host an Event', hosting_path %>
      <%= nav_link 'Interest Form', interest_form_path %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "RailsBridge.org"
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1" }
    %meta{ content: content_for?(:description) ? yield(:description) : "RailsBridge", name: "description" }
    %meta{ charset: "UTF-8" }
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = analytics_init if Rails.env.production?
    = csrf_meta_tags
    = favicon_link_tag 'icons/favicon.ico'
  %body{ class: (params[:controller]), id: (params[:action]) }
    = render "layouts/header"
    = render "layouts/subnav"
    = render "layouts/home_header" if params[:action] == 'home'
    .container
      .content
        - flash.each do |name, msg|
          %div{ class: "alert alert-#{name == :notice ? 'success' : 'danger'}" }= msg

        = yield

    = render "layouts/footer"

app/views/logistics/_sitemap.html.haml
.row
  - nav_links_by_group.each do |nav_group, links|
    %ul.sitemap
      %li
        %h4= nav_group.to_s.titleize
      - links.each do |link_info|
        %li= link_to link_info[0], link_info[1]

app/views/logistics/error_404.html.haml
- provide(:title, page_title(['Page Not Found']))

%h1 Not all those who wander are lost.
%h3 Though perhaps what you are really looking for is in one of the links above or below...

.container
  = render 'sitemap'

.error-code.hide-on-mobile 404

app/views/logistics/error_500.html.haml
!!!
%html
  %head
    %title RailsBridge | Server Error
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1" }
    %meta{ charset: "UTF-8" }
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = analytics_init if Rails.env.production?
    = csrf_meta_tags
  %body
    .container
      #error_500.logistics
        .content
          %h1 There has been an internal server error.
          %h3 This error is being logged and reported...

          %p If you need assistance or found a persisting problem please #{ link_to "create an issue", "https://github.com/railsbridge/railsbridge_dot_org/issues/new" } on GitHub.

          .error-code.hide-on-mobile
            %i.fa.fa-gears

app/views/logistics/sitemap.html.haml
- provide(:title, page_title(['Site Map']))

%h1 Site Map

= render 'sitemap'

app/views/shared/_event.html.haml
.event.js-match-height-item
  %h4= event.title
  %ul
    %li
      .event-date= event.event_dates
      .event-location= event.location_city
    %li
      %span.fa.fa-user
      = "Organized by #{event.organizers.first} & friends"
    %li
      = link_to event.location_url, class: 'event-venue', target: '_blank' do
        - if event.valid_location?
          %span.fa.fa-map-marker
        - if event.location_name.present?
          = "Held at #{event.location_name}"

    .event-cta
      = link_to event.signup_link, event.event_url, target: '_blank'

app/views/shared/_event_help.html.haml
.event-help.js-match-height-item
  %h4 Not Finding a Workshop?
  %p
    There are communities around the world that hold workshops. If
    there isn't one in your area, we'd love to help you get one started.
  %ul
    %li= link_to 'Check Out Local Chapters', :chapters, class: 'inline-link'
    %li= link_to 'Organize a Workshop', :organize, class: 'inline-link'

app/views/shared/_events.html.haml
- if events.present?
  - span_count = 12 / events_per_row
  - events.each_slice(events_per_row) do |event_row|
    .row.js-match-height
      - event_row.each do |event|
        %div{ class: "col-md-#{span_count}" }
          = render 'shared/event', event: event

app/views/shared/_events_with_help.html.haml
- if events.present?
  - count = 0
  - event_count = events.count
  - span_count = 12 / events_per_row
  - event_modulus = event_count % events_per_row

  - events.each_slice(events_per_row) do |event_row|
    .row.js-match-height
      - event_row.each do |event|
        %div{ class: "col-md-#{span_count}" }
          = render 'shared/event', event: event
        - if event_modulus > 0 && event_count == (count += 1)
          %div{ class: "col-md-#{span_count}"}
            = render 'shared/event_help'

  - if event_modulus == 0
    .row
      %div{ class: "col-md-#{span_count}" }
        = render 'shared/event_help'
- else
  %p Please visit #{ link_to "Bridge Troll", "http://www.bridgetroll.org/" } for our list of current events.

app/views/shared/_github_links.html.haml
You can either make a
#{ link_to "pull request", "https://github.com/railsbridge/railsbridge_dot_org", class: 'inline-link highlight' }
#{ defined?(cautious) ? '(if you know how)' : '' } or
#{ link_to "create an issue", "https://github.com/railsbridge/railsbridge_dot_org/issues/new", class: 'inline-link highlight' }#{ defined?(cautious) ? ' (no technical knowledge required)' : '' }.

app/views/static_pages/_mailing_list.html.haml
.feature.js-match-height-item
  .feature-icon.fa.fa-envelope-o
  %h4 Join the mailing list
  %p
    If you’d like to help maintain the curriculum or installfest, do meta-organizational things,
    or just have a great time with people who love teaching programming, join the
    #{link_to "workshop mailing list/Google group", "https://groups.google.com/forum/#!forum/railsbridge-workshops", class: 'inline-link'}.

app/views/static_pages/brand.html.haml
- provide(:title, page_title(['Brand']))

.row
  %h1 Brand Guidelines

  %p
    The RailsBridge board commissioned a new logo and brand identity for RailsBridge in the spring of 2016.
    You can learn more about how it came to be in
    #{ link_to "this very fun blog post", "https://blog.railsbridge.org/2016/03/21/railsbridge-has-a-new-logo/", target: "_blank" }!

  %h2 The Logo

  %p
    Here's our main logo as a .png in color and black and white:

  %p.mt30= image_tag "railsbridge-logos/railsbridge_horizontal_orange.png", width: 500

  %p.mt30.mb20= image_tag "railsbridge-logos/railsbridge_horizontal_black.png", width: 500

  %p
    You can also download all the permutations of the RailsBridge logo in
    #{ link_to "one zip file", "https://www.dropbox.com/s/8zw5jg2nfg404zm/railsbridge_logos.zip?dl=0", target: "_blank" } from a Dropbox folder. It's about 18MB.

  %p The #{ link_to "full logo folder", "https://www.dropbox.com/s/8zw5jg2nfg404zm/railsbridge_logos.zip?dl=0", target: "_blank" } includes:

  %ul.bulleted
    %li The above logo in orange, black, and white (for use on dark backgrounds)
    %li
      The following file formats: <span class="bold">.jpg, .png, .svg, .ai,</span> and <span class="bold">.eps</span>
    %li A stacked version of the logo, with the RailsBridge ruby centered above the word RailsBridge, for use where a vertical logo fits better.

  %h3 Chapter Logos

  %p
    Please email #{ mail_to "hello@railsbridge.org" } if you'd like us to make a chapter-specific version of the logo for you! Here are some examples:

  %p= image_tag "railsbridge-logos/chapter_logo_examples.jpg", width: 300

  %p
    (Please do get in touch, rather than trying to make a chapter logo yourself!
    We've bought licenses for the fonts and are very excited to put them to use.)

  .col-md-6
    %h2 Colors and Fonts

    %p Our fonts are Tisa Sans Pro Regular and Bold.

    %p The RailsBridge colors are mostly oranges and reds:

    %table.color-table
      %tr
        %td.main-orange
          \#EB6852
        %td.accent-deep-red
          \#B3282D
        %td.accent-red
          \#831A27

  .col-md-6
    %h2 Avoiding Common Mistakes

    %h3 Good:
    %ul.bulleted
      %li RailsBridge as a single word
      %li RailsBridge with the "R" and the "B" capitalized
    %h3 Bad:
    %ul.bulleted
      %li Rails Bridge with a space in the middle
      %li Railsbridge or railsbridge, without the "R" and the "B" capitalized

app/views/static_pages/donate.html.haml
.col-md-12
  %h1 Help RailsBridge Change the World

.col-md-9
  %h3 RailsBridge is run entirely on donations of money, time, and expertise.

  %p
    If your company or organization can help us make tech more welcoming and more diverse,
    we'd love your help. We need workshops sponsors (mostly to cover the cost of food), and also
    program sponsors so that we can help workshops happen in new places that don't yet
    have companies to help sponsor and host!

  %p
    RailsBridge works with #{ link_to "Bridge Foundry", "https://bridgefoundry.org/", class: 'inline-link' }, a 501(c)3 charitable organization, so that we're
    able to accept tax deductible donations.

  %p
    Wondering why supporting RailsBridge is a great idea? Head over to our #{ link_to "Donor FAQ", donor_faq_path, class: 'inline-link' }
    for answers.

.col-md-3
  %h5 Support RailsBridge:
  %form{action: "https://www.paypal.com/cgi-bin/webscr", method: "post", target: "_top"}
    %input{name: "cmd", type: "hidden", value: "_s-xclick"}/
    %input{name: "hosted_button_id", type: "hidden", value: "GFK2C4AJUW3G8"}/
    %input{alt: "PayPal - The safer, easier way to pay online!", border: "0", name: "submit", src: "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif", type: "image"}/
    %img{alt: "", border: "0", height: "1", src: "https://www.paypalobjects.com/en_US/i/scr/pixel.gif", width: "1"}/
  %h6 All donations are provided to Bridge Foundry, Inc. as #{ link_to "unrestricted funds", "https://rebrand.ly/bridge-foundry-unrestricted-funds" }.

  %h6 Email #{ mail_to("hello@railsbridge.org", nil, class: 'inline-link') } for more information.

app/views/static_pages/events.html.haml
- provide(:title, page_title(['Upcoming Workshops']))

.upcoming-events.js-match-heights
  %h1 Upcoming Events
  %p Delivered fresh by #{link_to 'Bridge Troll', "http://www.bridgetroll.org", class: 'inline-link'}, our event management software.
  = render 'shared/events_with_help', events_per_row: 3, events: @railsbridge_events

  - if @other_events.present?
    %h1 Events from our friends
    = render 'shared/events', events_per_row: 3, events: @other_events

app/views/static_pages/helping.html.haml
- provide(:title, page_title(['Helping']))

%h1 Want to help RailsBridge?
%h2 There are so many ways you can!
%h3 Teachers, TAs, Organizers and Sponsors Needed
%p The most visible volunteer positions within RailsBridge are the worshop sponsors, organizers, teachers, and TAs. They make each workshop happen!
%p
  If you're interested in teaching, check out the #{link_to "RailsBridge chapters", chapters_path} to see if one is coming up near you.
%p
  If you're interested in organizing, check out the #{link_to "organizing page", :organizing} and #{link_to "fill out our short interest form", :interest_form}!
%p If you're interested in sponsoring... todo...
.row
  .span6
    .feature-list
      .feature.clearfix.feature-1
        .feature-icon.icon-3x.icon-book
        %h4 Teach or TA
        %ul
          %li= link_to 'Teaching Resources', teaching_path
          %li= link_to 'Chapter List', chapters_path
          %li= link_to 'Upcoming Events', events_path
  .span6
    .feature-list
      .feature.clearfix
        .feature-icon.icon-3x.icon-cogs
        %h4 Organize, Sponsor or Host an Event
        %ul
          %li= nav_link 'Organize an Event', organizing_path
          %li= link_to 'Hosting Resources', hosting_path
          %li= nav_link 'Donor FAQ', donor_faq_path
.row
  .span12
    = render 'mailing_list'
.row
  .span12
    %h2 So many other ways to help, too!
    %p
      There are
      %em ton
      of other things that have to happen to keep RailsBridge thriving. If you can help us with any of these things, fill out our quick #{link_to "volunteer interest form", interest_form_path} and we will be in touch.
.row
  .span3
    .feature-list.horizontal-feature
      .feature.clearfix.feature-1
        .feature-icon.icon-3x.icon-book
        %h4 Curriculum Stuff
        %ul
          %li Maintain and create new curricula
          %li Keeping the constantly-changing Installfest up-to-date
          %li Help our teachers level up by creating more in-depth teacher training
  .span3
    .feature-list.horizontal-feature
      .feature.clearfix
        .feature-icon.icon-3x.icon-wrench
        %h4 Building Tools
        %ul
          %li We're trying to make organizing easier with Bridge Troll, an open source app we're buidling
          %li We want to make tools to help students figure out what to learn next!
  .span3
    .feature-list.horizontal-feature
      .feature.clearfix
        .feature-icon.icon-3x.icon-bullhorn
        %h4 Communicating
        %ul
          %li We need to tell the world what we're doing! PR dabblers welcome!
          %li Blogging. Writers are the best.
          %li Tweeting, Facebooking, LinkedIn-ing: social media is fun.
  .span3
    .feature-list.horizontal-feature
      .feature.clearfix
        .feature-icon.icon-3x.icon-phone
        %h4 Strategy and Fundraising
        %ul
          %li We're building an organization called Bridge Foundry to help us (and other orgs) manage our funds (and people) better!
          %li RailsBridge is growing a ton, and we can always use strategists and do-ers to help us think big and make those epic plans a reality
%br/
%h3.deemphasize TODO: Add more detail about the curriculum contribution process here or within the curriculum box...

app/views/static_pages/learning_resources.html.haml
- provide(:title, page_title(['Resources']))

%h1 What next? Write code every day!

.row.js-match-height
  .col-md-4
    .feature.js-match-height-item
      .feature-icon.fa.fa-bolt
      %h4 Pick something and get started
      %ul
        %li
          %p 
            This is the most important thing: pick your next project
            \&mdash;
            a tutorial, a class, or building your own app
            \&mdash;
            and get started right away. Momentum is important.
  .col-md-4
    .feature.js-match-height-item
      .feature-icon.fa.fa-envelope
      %h4 Keep in touch
      %ul
        %li
          %p Reach out to the people you connected with at your workshop. Coding with other people around is really motivating, plus you get to help each other solve trickier stuff.
  .col-md-4
    .feature.js-match-height-item
      .feature-icon.fa.fa-thumbs-up
      %h4 More RailsBridge
      %ul
        %li
          %p Come back to another workshop as a student, TA, or teacher. Teaching is a really great way to learn, too. (You'll be ready to TA sooner than you think, so don't be shy!)

%h2 Resources for you

#learning-resources-nav
  %ul.nav.nav-tabs
    %li.ruby.active= link_to "Ruby", "#ruby", class: 'inline-link'
    %li.rails= link_to "Rails", "#rails", class: 'inline-link'
    %li.front-end= link_to "HTML, CSS, & JavaScript", "#front-end", class: 'inline-link'
    %li.other= link_to "Other Web Development Fun", "#other", class: 'inline-link'
  .learning-resources
    #ruby
      = render partial: 'static_pages/resources/ruby_resources'
    #rails{style: 'display: none;'}
      = render partial: 'static_pages/resources/rails_resources'
    #front-end{style: 'display: none;'}
      = render partial: 'static_pages/resources/front_end_resources'
    #other{style: 'display: none;'}
      = render partial: 'static_pages/resources/general_web_dev_resources'